version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_app
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./static:/static
      - ./app/uploads:/app/uploads
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    expose:
      - "8000"
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build: .
    container_name: celery_worker
    command: celery -A app.broker.celery worker --loglevel=info --queues=default
    volumes:
      - ./app:/app/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./app/uploads:/app/uploads
      - ./ssl:/app/ssl:ro  # Cloudflare origin certificate
    depends_on:
      - api

volumes:
  postgres_data: