import os
from dotenv import load_dotenv


load_dotenv()
POSTGRES_USER=os.environ.get('POSTGRES_USER')
POSTGRES_PASSWORD=os.environ.get('POSTGRES_PASSWORD')
POSTGRES_DB=os.environ.get('POSTGRES_DB')
DATABASE_URL=os.environ.get('DATABASE_URL')
REDIS_URL=os.environ.get('REDIS_URL')
ALGORITHM = os.environ.get("ALGORITHM")
SECRET_KEY = os.environ.get("SECRET_KEY")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.environ.get("ACCESS_TOKEN_EXPIRE_MINUTES"))


GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")

FACEBOOK_CLIENT_ID = os.getenv("FACEBOOK_CLIENT_ID")
FACEBOOK_CLIENT_SECRET = os.getenv("FACEBOOK_CLIENT_SECRET")
FACEBOOK_REDIRECT_URI = os.getenv("FACEBOOK_REDIRECT_URI")

MAIL_USERNAME=os.getenv("MAIL_USERNAME")
MAIL_PASSWORD=os.getenv("MAIL_PASSWORD")
MAIL_SERVER=os.getenv("MAIL_SERVER")
MAIL_PORT=int(os.getenv("MAIL_PORT"))
MAIL_FROM=os.getenv("MAIL_FROM")
MAIL_FROM_NAME=os.getenv("MAIL_FROM_NAME")
DOMAIN=os.getenv("DOMAIN")
FULLDOMAIN=os.getenv("FULLDOMAIN")